[package]
name = "void-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
eyre = "0.6.12"
gtk4 = { version = "0.9.6", features = ["v4_16"] }
gtk4-layer-shell = "0.5.0"
pango = "0.20.10"
serde_json = "1.0.140"
